[global]
   server string = SynaBoot SMB Lab
   workgroup = WORKGROUP
   server role = standalone server
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   disable netbios = yes
   smb ports = 445
   interfaces = 0.0.0.0/0
   bind interfaces only = no
   hosts allow = 10.101.8. 127.
   hosts deny = ALL
   min protocol = SMB2
   server min protocol = SMB2
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   usershare allow guests = no
   restrict anonymous = 2

[synaboot-images]
   path = /srv/synaboot/images
   comment = SynaBoot image repository read-only lab share
   browseable = yes
   read only = yes
   writable = no
   guest ok = no
   valid users = synaboot
   force user = nobody
   force group = nobody
   create mask = 0444
   directory mask = 0555

[hotpe-mods]
   path = /srv/synaboot/images/pe/hotpe/runtime/HotProgMods
   comment = HotPE HPM runtime modules read-only lab share
   browseable = yes
   read only = yes
   writable = no
   guest ok = no
   valid users = synaboot
   force user = nobody
   force group = nobody
   create mask = 0444
   directory mask = 0555

[win11]
   path = /srv/synaboot/images/windows/win11
   comment = Windows 11 image source read-only lab share
   browseable = yes
   read only = yes
   writable = no
   guest ok = no
   valid users = synaboot
   force user = nobody
   force group = nobody
   create mask = 0444
   directory mask = 0555
